### ISSUE TITLE
Google cloud deploy command in thunder CLI

### ISSUE THREAD

**Issue by Raezil** [Raezil/Thunder#68]

**Comment by Raezil** [comment]
# 🚀 Deploy `raezil/app:latest` to Google Kubernetes Engine (GKE)
This tutorial will guide you through deploying your Docker image to Google Cloud's Kubernetes Engine (GKE).

## ✅ Prerequisites
Make sure the following tools are installed:
- [Google Cloud SDK](https://cloud.google.com/sdk/docs/install)
- `kubectl`
- A Google Cloud project

## 🔐 Step 1: Authenticate with Google Cloud
```bash
gcloud auth login
gcloud config set project YOUR_PROJECT_ID
```
Replace `YOUR_PROJECT_ID` with your actual GCP project ID.

## ⚙️ Step 2: Enable Kubernetes Engine API
```bash
gcloud services enable container.googleapis.com
```

## ☁️ Step 3: Create a GKE Cluster
```bash
gcloud container clusters create raezil-cluster --zone us-central1-a --num-nodes 1
```

## 🔗 Step 4: Configure `kubectl`
```bash
gcloud container clusters get-credentials raezil-cluster --zone us-central1-a
```

## 📦 Step 5: Create the Deployment
Create a file named `deployment.yaml`:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: raezil-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: raezil
  template:
    metadata:
      labels:
        app: raezil
    spec:
      containers:
        - name: raezil-container
          image: raezil/app:latest
          ports:
            - containerPort: 8080
            - containerPort: 50051
```

## 🌐 Step 6: Create the Service
Create a file named `service.yaml`:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: raezil-service
spec:
  type: LoadBalancer
  selector:
    app: raezil
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: grpc
      port: 50051
      targetPort: 50051
```

## 🚀 Step 7: Deploy to Kubernetes
```bash
kubectl apply -f deployment.yaml
kubectl apply -f service.yaml
```

## 🌍 Step 8: Get the External IP
```bash
kubectl get svc raezil-service
```
Wait until the `EXTERNAL-IP` is assigned. Use it to access your app.

## 🧠 Notes
- If your image is **private**, configure an `imagePullSecret`.
- To scale the deployment:
```bash
kubectl scale deployment raezil-app --replicas=3
```

Happy shipping! 🚢
